# wrangler release file
name = "desmos-proxy"
main = "worker.js"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "cootshk.dev/_/*", zone_name = "cootshk.dev" },
]

workers_dev = false

no_bundle = true
